// TODO: Akira: should be auto generated by scripts(also svg-images => icons)
// ticket: https://app.clickup.com/t/908879/G123DEV-24941
export { default as ChatOutlined } from './icons/ChatOutlined';
export { default as EarthOutlined } from './icons/EarthOutlined';
export { default as GameOutlined } from './icons/GameOutlined';
export { default as HomeOutlined } from './icons/HomeOutlined';
export { default as NotificationOutlined } from './icons/NotificationOutlined';
export { default as ProfileOutlined } from './icons/ProfileOutlined';
export { default as ChevronUpOutlined } from './icons/ChevronUpOutlined';
export { default as ChevronDownOutlined } from './icons/ChevronDownOutlined';
export { default as ChevronLeftOutlined } from './icons/ChevronLeftOutlined';
export { default as ChevronRightOutlined } from './icons/ChevronRightOutlined';
export { default as CloseOutlined } from './icons/CloseOutlined';

export { default as ChatFilled } from './icons/ChatFilled';
export { default as EarthFilled } from './icons/EarthFilled';
export { default as GameFilled } from './icons/GameFilled';
export { default as HomeFilled } from './icons/HomeFilled';
export { default as NotificationFilled } from './icons/NotificationFilled';
export { default as ProfileFilled } from './icons/ProfileFilled';

export { default as ChatTwoTone } from './icons/ChatTwoTone';
export { default as EarthTwoTone } from './icons/EarthTwoTone';
export { default as GameTwoTone } from './icons/GameTwoTone';
export { default as HomeTwoTone } from './icons/HomeTwoTone';
export { default as NotificationTwoTone } from './icons/NotificationTwoTone';
export { default as ProfileTwoTone } from './icons/ProfileTwoTone';
