// TODO: Akira: should be auto generated by scripts(also svg-images => icons)
// ticket: https://app.clickup.com/t/908879/G123DEV-24941
export { default as AccountRecoveryOutlined } from './icons/AccountRecoveryOutlined';
export { default as ChatOutlined } from './icons/ChatOutlined';
export { default as CopyOutlined } from './icons/CopyOutlined';
export { default as DocumentOutlined } from './icons/DocumentOutlined';
export { default as DownloadOutlined } from './icons/DownloadOutlined';
export { default as EarthOutlined } from './icons/EarthOutlined';
export { default as ExclamationOutlined } from './icons/ExclamationOutlined';
export { default as FileOutlined } from './icons/FileOutlined';
export { default as GameOutlined } from './icons/GameOutlined';
export { default as HomeOutlined } from './icons/HomeOutlined';
export { default as NotificationOutlined } from './icons/NotificationOutlined';
export { default as PaymentOutlined } from './icons/PaymentOutlined';
export { default as ProfileOutlined } from './icons/ProfileOutlined';
export { default as ChevronUpOutlined } from './icons/ChevronUpOutlined';
export { default as ChevronDownOutlined } from './icons/ChevronDownOutlined';
export { default as ChevronLeftOutlined } from './icons/ChevronLeftOutlined';
export { default as ChevronRightOutlined } from './icons/ChevronRightOutlined';
export { default as CloseOutlined } from './icons/CloseOutlined';
export { default as LoadingOutlined } from './icons/LoadingOutlined';
export { default as StarOutlined } from './icons/StarOutlined';
export { default as StarHalfOutlined } from './icons/StarHalfOutlined';
export { default as SecurityOutlined } from './icons/SecurityOutlined';

export { default as ChatFilled } from './icons/ChatFilled';
export { default as CopyFilled } from './icons/CopyFilled';
export { default as EarthFilled } from './icons/EarthFilled';
export { default as ExclamationFilled } from './icons/ExclamationFilled';
export { default as GameFilled } from './icons/GameFilled';
export { default as HomeFilled } from './icons/HomeFilled';
export { default as NotificationFilled } from './icons/NotificationFilled';
export { default as ProfileFilled } from './icons/ProfileFilled';
export { default as StarFilled } from './icons/StarFilled';
export { default as StarHalfFilled } from './icons/StarHalfFilled';

export { default as ChatTwoTone } from './icons/ChatTwoTone';
export { default as CopyTwoTone } from './icons/CopyTwoTone';
export { default as EarthTwoTone } from './icons/EarthTwoTone';
export { default as ExclamationTwoTone } from './icons/ExclamationTwoTone';
export { default as GameTwoTone } from './icons/GameTwoTone';
export { default as HomeTwoTone } from './icons/HomeTwoTone';
export { default as NotificationTwoTone } from './icons/NotificationTwoTone';
export { default as ProfileTwoTone } from './icons/ProfileTwoTone';
export { default as StarTwoTone } from './icons/StarTwoTone';
export { default as StarHalfTwoTone } from './icons/StarHalfTwoTone';
